#!/bin/bash
# Run this script to commit all new commodity files to git
# Generated by Claude Code

set -e

git add \
  backend/ai/agents/concrete/commodity_ai_agent.py \
  backend/ai/agents/skills/commodities/__init__.py \
  backend/ai/agents/skills/commodities/commodity_signals.py \
  backend/ai/agents/concrete/swarm_manager.py \
  backend/commodities/base.py \
  backend/commodities/cot_positioning.py \
  backend/commodities/curve_analytics.py \
  backend/commodities/signal_hub.py \
  backend/strategies/commodities/battery_metals_ev_demand.py \
  backend/strategies/commodities/carbon_credits_eua.py \
  backend/strategies/commodities/copper_gold_ratio_economy.py \
  backend/strategies/commodities/corn_soybean_crush.py \
  backend/strategies/commodities/lng_henry_hub_ttf_arb.py

git commit -m "Commodities section rebuild: satellite+AIS+COT+curve+AI agent wiring

Core infrastructure:
- backend/commodities/base.py: CommodityStrategy base class, CommoditySignal
  dataclass, SignalDirection/SignalSource enums, aggregate_signals()
- backend/commodities/curve_analytics.py: ForwardCurve, roll_yield,
  crack/spark/dark/crush/frac spreads, Nelson-Siegel fitting, carry_signal
- backend/commodities/cot_positioning.py: COTEngine (crowding+momentum
  composite), cot_signals_from_df vectorized pipeline
- backend/commodities/signal_hub.py: CommoditySignalHub aggregating
  satellite NDVI, AIS vessel tracking, EIA inventory, COT, curve, weather

Strategies (institutional class-based):
- backend/strategies/commodities/lng_henry_hub_ttf_arb.py: HH/TTF/JKM
  logistics-adjusted spread + EU storage + seasonal demand
- backend/strategies/commodities/corn_soybean_crush.py: GPM crush margin
  z-score, corn-soy planting ratio, satellite NDVI drought overlay
- backend/strategies/commodities/carbon_credits_eua.py: fuel-switching
  implied carbon price, regulatory calendar (surrender/TNAC), UK ETS arb
- backend/strategies/commodities/battery_metals_ev_demand.py: Ni/Co/Li/Mn
  EV adoption curve, cathode chemistry (NMC vs LFP), class I spread,
  satellite mine nightlights, AIS chemical tanker utilization
- backend/strategies/commodities/copper_gold_ratio_economy.py: Dr. Copper
  macro regime, Cu/Au vs 10y yield divergence, China PMI, Chile/Peru supply

AI agent layer:
- backend/ai/agents/concrete/commodity_ai_agent.py: CommodityAIAgent
  wiring all strategies + CommoditySignalHub into BaseAgent framework;
  produces ranked TradeIdea list + macro regime + CommodityBrief
- backend/ai/agents/skills/commodities/commodity_signals.py: skill module
  with get_commodity_brief, get_cot_signal, get_carry_signal,
  get_macro_regime, get_fuel_switching_signal, get_ev_demand_score
- backend/ai/agents/concrete/swarm_manager.py: added CommodityAIAgent
  (10th agent), _map_from_commodity mapper, playbook_commodity_brief DAG

Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"

echo "Commit successful!"
