---
apiVersion: v1
kind: Namespace
metadata:
  name: analytics
  labels:
    project: hyper-os
    tier: analytics
    istio-injection: enabled

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-controller
  namespace: analytics

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
  namespace: analytics

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows
rules:
  - apiGroups: ["argoproj.io"]
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
      - workflowtasksets
      - workfloweventbindings
    verbs: ["*"]

  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/exec
      - secrets
      - configmaps
      - events
      - persistentvolumeclaims
      - serviceaccounts
    verbs: ["*"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["create", "get", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows
subjects:
  - kind: ServiceAccount
    name: argo-workflow-controller
    namespace: analytics
  - kind: ServiceAccount
    name: argo-server
    namespace: analytics

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: analytics
data:
  containerRuntimeExecutor: emissary

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      serviceAccountName: argo-workflow-controller
      containers
        :
        - name: workflow-controller
          image: quay.io/argoproj/workflow-controller:v3.5.0
          args:
            - --configmap
            - workflow-controller-configmap
          ports:
            - containerPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      serviceAccountName: argo-server
      containers:
        - name: argo-server
          image: quay.io/argoproj/argocli:v3.5.0
          args:
            - server
            - --namespaced
            - --auth-mode=server
          ports:
            - containerPort: 2746