---
apiVersion: v1
kind: Namespace
metadata:
  name: analytics

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-operator
  namespace: analytics

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clickhouse-operator
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
      - events
    verbs: ["*"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs: ["*"]

  - apiGroups: ["clickhouse.altinity.com"]
    resources:
      - clickhouseinstallations
      - clickhouseinstallations/status
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clickhouse-operator
subjects:
  - kind: ServiceAccount
    name: clickhouse-operator
    namespace: analytics

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-operator
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-operator
  template:
    metadata:
      labels:
        app: clickhouse-operator
    spec:
      serviceAccountName: clickhouse-operator
      containers:
       :
        - name: operator
          image: altinity/clickhouse-operator:0.23.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888